steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - ci-cd-cf # Function name
    - --region=us-central1
    - --source=.
    - --trigger-http
    - --runtime=nodejs16
  id: 'deploying-a-serverless-function'